name: liquidsoap # you probably want to 'snapcraft register <name>'
base: core18
version: '1.4.0'
summary: Swiss-army knife for multimedia streaming
description: |
  Liquidsoap is a powerful and flexible language for describing your
  streams. It offers a rich collection of operators that you can combine
  at will, giving you more power than you need for creating or
  transforming streams. But liquidsoap is still very light and easy to
  use, in the Unix tradition of simple strong components working
  together.

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  liquidsoap:
    plugin: autotools
    source: https://github.com/savonet/liquidsoap/releases/download/1.4.0/liquidsoap-1.4.0.tar.bz2
    build-packages: [ocaml]
